export const SET_TRIPS = "SET_TRIPS";
export const ADD_TRIP_TO_CART = "ADD_TRIP_TO_CART";
export const REMOVE_TRIP_FROM_CART = "REMOVE_TRIP_FROM_CART";
export const SET_CATEGORIES = "SET_CATEGORIES";
export const UPDATE_CURRENT_CATEGORY = "UPDATE_CURRENT_CATEGORY";
export const CLEAR_CART = "CLEAR_CART";
